### ISSUE TITLE
Remove example artifacts from the repository

### ISSUE THREAD

**Issue by liberostelios** [NASA-AMMOS/3DTilesRendererJS#124]
It is considered a bad practice to contain the artifacts of a code in a repository, while the source code is there. Currently, whenever an example is changed you have to commit so many unnecessary file changes. I suggest that the `./example/bundle` folder is added to `.gitignore`.

I understand that hosting the compiled version is useful for github.io, but there is a way to have one branch (normally `gh-pages`) which only contains the examples and pages and is created ad-hoc every time you want to deploy a new version of the examples. We do something similar with another project using [this](https://github.com/cityjson/ninja/blob/main/deploy.sh) script to deploy the artifacts.

I could set up something similar for you. The only downside of that is that you would have to call the `./deploy.sh` script manually, every time you need the examples updated in the page, instead of having them updated with every commit.

**Comment by gkjohnson** [comment]
I'm not sure if I see it as poor practice but I'll think about it a bit. Having the example builds in the master doesn't bother me and otherwise only seems to be a minor inconvenience when making commits. I don't expect the build changes to be committed in PRs, though. If anything I think it would be nice to auto build on every commit to master -- maybe github actions can be used to do this? I don't know a whole lot about them though.

**Comment by liberostelios** [comment]
I now realise that this might have come off slightly different than I meant it and, thus, might need perceived as mildly judgemental. I didn't mean that this is a case of bad practice, per se, but that there is a common suggestion that those things better be avoided, which might be something to take under consideration here. I am sorry that I didn't make that clear in the first place.

I personally think there are valid exceptions to the rule because it's always about personal preference and convenience. For instance, when hosting LaTeX code in a git repo I also include the PDF because it's far easier to have it available there.

The downside of this is that you often get unnecessary conflicts or changes. For instance, when running the example I get changes to all files in the `bundle` folder, even if nothing has changed to the source code. That's a bit confusing (and I admit it also triggers my OCD :-) ) but nothing that can't be solved by just ignoring the changes in certain commits.

It should be possible to have an action that updates the pages automatically and that's probably the best choice, if you want to go down that road. I can investigate that if you are interested. But if you are comfortable with the current situation then it might be better to just ignore my suggestion altogether, at least for now. As soon as only few people are involved with the repo this isn't a big issue.

**Comment by gkjohnson** [comment]
Oh I didn't take it that way! I understand we all have different preferences and workflows and take all these suggestions as well intentioned. I think in this case it's a minor inconvenience and my preference is to keep all relevant code in a single place instead of spreading it across branches. This is also how I've structure the other projects I maintain and as much as possible I'd like to retain a consistent workflow across projects so I don't have to recall how the different build processes are structured in different repos to reduce mental overhead.

Regarding build files changing even though there's no actual diff I've noticed that too -- I'm not sure if it's a line endings issue or what but perhaps that can be handled separately. Maybe it's a setting in Parcel?

I think for now I'll want to keep things the way they are if you don't mind and mull on this for a while because I do agree it can be a bit confusing for newcomers. I do appreciate you bringing it up though!

**Comment by liberostelios** [comment]
Thank you for taking this under consideration. Working like this is totally fine with me. I'll keep in mind that for PRs I won't commit the changes of the artifacts. In fact, it might be useful to mention something about this in the README for other potential contributors?

Indeed, there might be a way to set Parcel so that there are less changes every time. I am not sure what it is, as I am very bad with those JS building tools, I have to admit.

**Comment by dbuck** [comment]
It's probably ok early on, and I get the easy serving/updating is helpful but over time it will add up in the git history.

Updating the full /examples/bundle folder in a build commit is adding +30mb to non-shallow clones?

**Comment by gkjohnson** [comment]
I'd be very interested in getting some kind of github action going to automatically build this stuff so I don't have to commit it or consistently commit to to a different branch -- I just don't have the bandwidth to do the research on how to make that happen at the moment. If anyone is an expert and can get that going I'd happily take a PR for it. Or maybe someone can point to a tutorial or project that already has it set up.

I think ideally you'd be able to just add a Github action that makes the build and serves the files that are on the master branch with no extra manual effort on my part.

**Comment by gkjohnson** [comment]
I finally had a chance to look into this. I've just removed the examples bundles from the main branch and added a Github action to auto-commit the demo bundles to another branch for GH Pages. You can check the github action file out [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/.github/workflows/examples-build.yml)

Thanks again guys -- it hadn't occurred to me how quickly the builds would cause the repo to grow.
