### ISSUE TITLE
the relative position of the nodes seems like incorrect

### ISSUE THREAD

**Issue by Wincy94** [NASA-AMMOS/3DTilesRendererJS#148]
I loaded the model in threejs with the code in example/index.html.

It successfully loaded the model. but I find out the relative position of the nodes seems like incorrect. 
Here are the picture shows the difference:

![image](https://user-images.githubusercontent.com/26516358/104142070-d7a56b00-53f4-11eb-91fb-3c4805e1d059.png)

I am new to threejs, i don't know why it happened, it confused me.

**Comment by gkjohnson** [comment]
Hello @Wincy94! Are you able to provide the tile set for testing? Depending on the tile formats used and the semantics used its possible that your data is using features we don't support yet but it may not be hard to add them. It's primarily a matter of having available data to test.

**Comment by Wincy94** [comment]
> Hello @Wincy94! Are you able to provide the tile set for testing? Depending on the tile formats used and the semantics used its possible that your data is using features we don't support yet but it may not be hard to add them. It's primarily a matter of having available data to test.

I can give you some of b3dm belongs to this tile set. How can I send it to you?

**Comment by gkjohnson** [comment]
Great! I'll need to full tile set including the json file in order to verify and debug the issue, though. It's possible there's a bug elsewhere, as well.

Depending on the size of the tile set you can zip it and upload it in a comment in this issue (drag and drop) or email it to me (email is in my profile). If it's larger you can use something like drop box or google drive and send me the link.

**Comment by Wincy94** [comment]
I had send the tile set to your email. Thanks for your help~ 

> Great! I'll need to full tile set including the json file in order to verify and debug the issue, though. It's possible there's a bug elsewhere, as well.
> 
> Depending on the size of the tile set you can zip it and upload it in a comment in this issue (drag and drop) or email it to me (email is in my profile). If it's larger you can use something like drop box or google drive and send me the link.

**Comment by gkjohnson** [comment]
Thanks for the sample data @Wincy94. It turns out it was an incorrect use of `multiply` vs `premultiply` when computing world transforms which is a goofy mistake. It looks like all my test tile sets use identity transforms for all tiles so it wasn't causing issues anywhere else so I appreciate you raising the issue.

You can see the comparison shots in #151 which shows the fixed gap in the model you provided. I've published version v0.2.5 with this fix to npm. Do you mind updating your version and confirming it fixes your larger model, as well?

**Comment by gkjohnson** [comment]
Fixed in #151
