### ISSUE TITLE
Remove dependency on path library

### ISSUE THREAD

**Issue by Gmadges** [NASA-AMMOS/3DTilesRendererJS#197]
Projects that use webpack 5+ will display this error/warning

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

Wondering whether it would make sense to remove the dependency in the library by explicitly using `path-browserify`.
Alternatively we could opt to write the code internally, but it would probably be a copy of the `path-browserify` functionality and require added maintenance.
The downside of using `path-browserify` is that is only supports POSIX paths

It would be good to get some thoughts on this.

**Comment by gkjohnson** [comment]
Hello! That sounds good to me if you'd like to send a PR to use `path-browserify` instead of `path`. 

> Alternatively we could opt to write the code internally

I'm not against this considering we just really just use `path.join` and `path.dirname` if you'd like to give it a try and add tests but updating the dependency is clearly the easier path forward. I expect `path-browserify` is what bundlers are already including as a fallback anyway.
