### ISSUE TITLE
Cleanup Loader/LoaderBase classes

### ISSUE THREAD

**Issue by dbuck** [NASA-AMMOS/3DTilesRendererJS#224]
All the tile contents are being downloaded via `TilesRendererBase.requestTileContents`. Each of the *LoaderBase.js classes includes an unused .load function / fetch options in addition to the .parse function which is used to load the contents from the downloaded buffer.

While looking at extension support, do we want to clean up and remove these unused functions, or are they intended to be used for some future behavior?

**Comment by gkjohnson** [comment]
Hey @dbuck! I originally added the `.load` functions to align with the three.js loader APIs and make them easier to test independently. All of the [b3dmExample](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/b3dmExample.js#L124), [i3dmExample](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/i3dmExample.js#L66), and [pntsExample](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/pntsExample.js#L63) pages use the .load function to load the the files directly. And The i3dm loader uses `fetchOptions` [in the parse implementation](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/base/I3DMLoaderBase.js#L139) to load external GLTF data.

To that end I think I'd prefer to keep the functions for now if only to make testing easier. There is quite a bit of redundancy between loaders, though, with fetchOptions and the load implementations. I might be a good idea to add a shared `LoaderBase` class that implements the common "load" class and adds "fetchOptions" to avoid code duplication. Aside from that I haven't thought too much about potential applications for extension / 3d tiles 2.0 applications.

**Comment by dbuck** [comment]
Ahh! That makes sense, I had not looked in the examples, I was just looking at the main content load / and parse! 

The other thing I was noticing is that it isn't very consistent in the types about the response type of the .parse function, many (but not all) of the base loader files have a sync .parse, and the majority of the three extensions have the same async parse signature except for the synchronous PNTSLoader. 

I have a cleaned up GLTFExtensionLoader PR to open up, but I was thinking about shifting PNTs to match the others, and have a single map of loaders to extensions or magic.

I'll take a look at the different .load functions in the bases and see if there's good enough overlap to make sense for a LoaderBase, or to keep that separate?

**Comment by gkjohnson** [comment]
> The other thing I was noticing is that it isn't very consistent in the types about the response type of the .parse function, many (but not all) of the base loader files have a sync .parse, and the majority of the three extensions have the same async parse signature except for the synchronous PNTSLoader.

This was just by necessity. The I3DM loader needs to be async to load the external gltf contents. And the three.js implementation of B3DM is async because GLTFLoader parse is async. I don't have strong feelings on the API consistency here either way but I don't see a reason to convert the parse functions to all return promises, at the moment.

> I have a cleaned up GLTFExtensionLoader PR to open up, but I was thinking about shifting PNTs to match the others, and have a single map of loaders to extensions or magic.

Awesome to hear! I think I'm okay with keeping it simple right now and just adding support for GLTF to the existing `parseTile` function until we see that there are other file formats that people are using and what the requirements might be. With some other extensions and optimizations possible (like [multiple tiles loadable at once](https://github.com/CesiumGS/3d-tiles/issues/459#issuecomment-970761386) or the [multiple contents extension](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_multiple_contents)) there may be other ways to consider refactoring the parseTile function in the long run.

> I'll take a look at the different .load functions in the bases and see if there's good enough overlap to make sense for a LoaderBase, or to keep that separate?

`LoaderBase` sounds good to me!

**Comment by dbuck** [comment]
I'm going to close this discussion, the relevant parts were resolved by adding the LoaderBase in #230
