### ISSUE TITLE
Model's tiles disappear during loading process

### ISSUE THREAD

**Issue by alex-lancer** [NASA-AMMOS/3DTilesRendererJS#227]
Hey,

We download model with high level of details (`errorThreshold = 0`, `errorTarget = 0`), however during the download process some pieces / tiles of the model disappear (even if they are in the FOV of the camera)
Increasing of
```
tiles.lruCache.maxSize;
tiles.lruCache.minSize;
```
do not give good enough results
Can u please advise on how to perform model load without parts/tiles disapearing
Thanks in advance

PS: i think there is probably a case with queueing requests for tiles when required tiles are pushed to the end of the request queue however old tiles that are already not needed are still in the head

---
3d-tiles-renderer version 0.3.4

**Comment by gkjohnson** [comment]
Hello! If you set `errorThreshold` to `0` then only the very leaf tiles will load. Generally it's recommended that you keep `errorThreshold` set to `Infinity` unless you know the camera will be moving slowly between tiles.

Otherwise if you have behavior you think is incorrect it would be best to provide a demo of the poor loading behavior so it's more clear what is happening along with how you expect to behave, instead. Otherwise it's a bit difficult to imagine what the behavior is.
