### ISSUE TITLE
  Unnecessary models are picked up when picking 3d tiles model

### ISSUE THREAD

**Issue by familyaa** [NASA-AMMOS/3DTilesRendererJS#265]
When I use the `raycaster.intersectObject(scene)` method to get the object and change the `material,` I find that multiple models are changed.Is this something to do with the model organization structure?How do I correctly pick up the current model?
![image](https://user-images.githubusercontent.com/29749825/176129778-bec6be61-77f3-4b6e-98b0-6108392d6be1.png)
Looking forward to your help.
thanks

**Comment by gkjohnson** [comment]
When the same material is shared among objects or instanced items then all objects that share the material instance will change. You'll have to replace the material on just the clicked object if you want it to change separately.

**Comment by familyaa** [comment]
Thank you for your answer, but I found that multiple objects belong to the same `mesh` ,is there a way to pick out the object that i want it to change separately?

**Comment by gkjohnson** [comment]
It depends on what kind of file those meshes are loaded as. If they're instanced geometry they you should get the instance id as a result of the raycast. If they're loaded as a B3DM file then you can take a look at how the [b3dmExample file](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/3f02bcbc38bebfde4e74e99553f202275075cd12/example/b3dmExample.js#L173-L200) handles this. See the full example [here](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/b3dmExample.html).

Otherwise if all the geometry is just loaded as geometry you'll have to export your data differently, ufortunately.

**Comment by familyaa** [comment]
Thanks!
How to pass original material through `batchIdHighlightShaderMixin` method, can you give me some guidance?
![image](https://user-images.githubusercontent.com/29749825/176409493-76159b50-9b00-4e04-bc98-db7f6cb86fd9.png)

**Comment by gkjohnson** [comment]
For general three.js questions I recommend asking at the threejs forum:

https://discourse.threejs.org/

**Comment by familyaa** [comment]
Thanks again for your guidance.

**Comment by Michelle1009** [comment]
@gkjohnson  I use mesh.setColorAt( i, color ) to change instanced geometry color in my test, but it does not work. I add instance.setColorAt( i, new Color() ) in I3DMLoader then I can change the color in my test.
![image](https://user-images.githubusercontetnt.com/17328621/177895405-1a4b0931-0480-49d0-ba4b-aff1c8998985.png)
I try the threejs example which is the same way. https://github.com/mrdoob/three.js/blob/master/examples/webgl_instancing_raycast.html
![image](https://user-images.githubusercontent.com/17328621/177895803-be2d56b6-2bd9-4572-b2cb-c7a0caf656b6.png)
