### ISSUE TITLE
Please provide Example for locating a pieces of the geometry by batch id

### ISSUE THREAD

**Issue by JupiterStep** [NASA-AMMOS/3DTilesRendererJS#270]

**Comment by gkjohnson** [comment]
Can you provide more information about your use case and what you're trying to do

**Comment by JupiterStep** [comment]
I have a model of the city. The format of this model is 3dfiles. I need to locate a specific small building according to the field of batchtable.

 
`/**
 *
 * @param name  the name of model
 * @param camera THERR.PerspectiveCamera
 */
function locate (name, camera){
    // search in batchTable
    const scene  = tileRenderer.group;
    scene.traverse((c)=>{
        if(c.batchTable){
            const batchTable = c.batchTable;
            const names = batchTable.getData( 'name' );
            for (let i = 0; i < names.length; i++) {
                const nameStr = names[i];
                if(nameStr === name){
                    // TODO How to move the camera to the position of the model;
                }
            }
        }
    });
}`

**Comment by gkjohnson** [comment]
It depends on the data you have available. If your batch table includes information about the position or bounds of the given object you can use that to position the camera. Otherwise you'll have to extract the positions from the geometry and compute a bounds and position for manually based on the batch id attribute.

**Comment by JupiterStep** [comment]
I see. Thank you for your help
