### ISSUE TITLE
Model cannot be rendered

### ISSUE THREAD

**Issue by kingwangwang** [NASA-AMMOS/3DTilesRendererJS#317]
**Describe the bug**

**Comment by gkjohnson** [comment]
As the error indicates your tilesets are using a deprecated glTF format that Cesium still supports. If you want to render it you'll have to implement `LoadingManager.getHandler` and use a version of three.js GLTFLoader that supports the old format. But otherwise I'd recommend regenerating the tileset with glTF 2.0 contents.

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC

**Comment by kingwangwang** [comment]
> As the error indicates your tilesets are using a deprecated glTF format that Cesium still supports. If you want to render it you'll have to implement `LoadingManager.getHandler` and use a version of three.js GLTFLoader that supports the old format. But otherwise I'd recommend regenerating the tileset with glTF 2.0 contents.

thanks
