### ISSUE TITLE
Bounding box is undefined for sphere bounding volumes

### ISSUE THREAD

**Issue by jesse-small** [NASA-AMMOS/3DTilesRendererJS#334]
**Describe the bug**

When using a 3d-tile that uses sphere bounding volumes instead of box or region, we generate the sphere bounding object but never use that to populate a corresponding box bounding object. The other bounding methods will populate the missing objects.

Box -> populates bounding box and bounding sphere
Region -> populates bounding box and bounding sphere
Sphere -> only populates bounding sphere

**To Reproduce**

I can setup some public data if needed but looking at the code below it should be pretty straight forward to see the missing logic.

***Code***

```js
		let sphere = null;
		if ( 'sphere' in tile.boundingVolume ) {

			const data = tile.boundingVolume.sphere;
			sphere = new Sphere();
			sphere.center.set( data[ 0 ], data[ 1 ], data[ 2 ] );
			sphere.radius = data[ 3 ];
			sphere.applyMatrix4( transform );

		} else if ( 'box' in tile.boundingVolume ) {

			const data = tile.boundingVolume.box;
			sphere = new Sphere();
			box.getBoundingSphere( sphere );
			sphere.center.set( data[ 0 ], data[ 1 ], data[ 2 ] );
			sphere.applyMatrix4( transform );

		}
```

**Expected behavior**

When a sphere bounding volume is passed in that should also generate the corresponding bounding box.

Note: I am happy to push a PR up to add this logic, but I wanted to confirm if there was a reason the bounding box is not being populated already?

**Comment by gkjohnson** [comment]
Thanks for the report - the implicit population of other fields was primarily intended to support the need to have specific volumes in for the `tileInView` and `calculateError` functions. TileInView requires a sphere while calculateError uses the bounding box if it's available since we can assume it's the tightest bound. It's best to use the most accurate bounding shape in these functions - eventually it would be good to support implementations for all the bounding shapes so no implicit volumes would have to be generated but that's a problem for the future.

I think for the moment it would be best to add an implicit bounding box generation to the `getBoxBounds` and `getBounds` functions if the bounding box is not otherwise available. We should update the docs, as well, stating you may get an inflated bound if a box isn't provided with the tileset. In the future it may make sense to add some kind of function to check if a "native", tight oriented bounding box is provided - though we can wait until that's needed.

If that sounds good to you feel free to make a PR!

**Comment by jesse-small** [comment]
Here is the code I have put together to be added. This would run if there is no bounding box, and a sphere bounding volume is available.

```js
if ( box === null ) {

  box = new Box3();
  boxTransform = new Matrix4();
  boxTransformInverse = new Matrix4();
  
  sphere.getBoundingBox( box );
  boxTransform.premultiply( transform );
  boxTransformInverse.copy( boxTransform ).invert();

}
```

I have tested the above with a few local files with differing transforms on them and the bounding boxes look correct with what I would expect from the sphere volumes. I also tested other functionality such as raycasting which uses boundingBox and with this change raycasting now works correctly when using sphere volume 3d-tiles.

The only part I am not 100% sure of is the way I am calculating the boxTransform, please let me know your thoughts on this and I will push up a PR for review soon as well.

**Comment by gkjohnson** [comment]
> Since a lot of places use the "cached" bounding box which is set by the TilesRenderer, I was thinking it would make sense to check for a null box if the sphere volume is available, and then generating the bounding box from there.

Please add the generation in the getBoxBounds and getBounds functions. The `calculateError` function prefers [a bounding box if it exists](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/5b06c36c7a3965e5ffd2303a82a371cf1823a96a/src/three/TilesRenderer.js#L906) which means that adding a bounding box will always use that while the sphere is the better volume since the box will always be larger and less precise.

> Here is the code I have put together to be added. This would run if there is no bounding box, and a sphere bounding volume is available.

Your version should work. But this line can just be changed to a copy:

```js
  boxTransform.premultiply( transform );
  // can change to
  boxTransform.copy( transform );
```

**Comment by jesse-small** [comment]
Happy to make those changes.

The other change I'd need to make would be in raycastTraverse.js.

It currently checks the bounding sphere first before confirming a hit by using the bounding box. However if a bounding box does not exist, even if it the raycast hit a bounding sphere, it will still consider this a miss. I would like to add a check that if the bounding sphere was a hit and there is no bounding box, we consider that a hit.

**Comment by jesse-small** [comment]
Working through this I noticed an inconsistency. In the cache, we save the bounding box in its non-transformed state, then whenever we need to use it we will multiply it by the boxTransform. However the cached bounding sphere is saved in its transformed state, so the calculateError method for example will run incorrectly when using a bounding sphere with a transformation matrix since we find the distance between the transformed sphere and the un-transformed camera position. 

The bounding box calculation does not have this problem since its saved as un-transformed already.

Should we look at saving the bounding sphere as un-transformed and applying the transform when needed? That would give consistent behaviour with how the bounding box is used right now.

**Comment by jesse-small** [comment]
I have created a PR with my changes: https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/340
