### ISSUE TITLE
"GlobeControls" problem after calling setLatLonToYUp

### ISSUE THREAD

**Issue by tobias74** [NASA-AMMOS/3DTilesRendererJS#393]
Hello!

I am trying to adjust an existing GlobeControls component that enables the user to drag and pan around the globe without being fixed to one location on the globe. And everything works fine so far, but only as long as I do not call the function "setLatLonToYUp". The GlobeControls work perfectly rotating, panning and zooming the globe. 

But eventually I have to call "setLatLonToYUp" because I want to load models into the scene (GLTFLoader). The models appear very distorted in case I do not call "setLatLonToYUp". Also when the models are too far away from the original point that setLatLonToYUp was called with, they start to look distorted. So there is no way of getting around calling this function. But as soon as I do, the GlobeControls dont really work anymore, and instead of rotating the globe around its center, the globe is now rotated around the point on the surface that setLatLonToYUp has been called with.

So my question is: How can I compensate my GlobeControls for the changes introduced by calling setLatLonToYUp?

Or maybe there is a way to eliminate the distortions on the models without ever calling setLatLonToYUp?

Regards!
Tobias

**Comment by gkjohnson** [comment]
> ... I want to load models into the scene (GLTFLoader). The models appear very distorted in case...

Are your models animated? I'd expect this to only be a big issue with animated models.

There's not necessarily a "need" to call "setLatLonToYUp" - the important thing is that the geometry is kept near 0,0,0, which is that that function helps with. But this can be done manually, as well, either by moving the globe instead of the camera or moving the globe and camera as a group to position them in a spot that alleviates the precision issues before render.

As an aside - are you able to share the GlobeControls? If there are existing solutions for camera controls here it would be nice to include them in the project or at least direct users to them since it's of interest to others, as well (see #356)
