### ISSUE TITLE
GlobeControls: horizon can be clipped due to new horizon-based far plane

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#486]
See https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/483#issuecomment-1952550512

**Comment by AlaricBaraou** [comment]
It's not taking the direction into account indeed but it's on purpose. Normally it's accounting for the furthest distance possible in all direction from the given coordinates.

**Comment by AlaricBaraou** [comment]
For this particularly extreme case it's mostly because the elevation goes close to 0 while we're still above ground.

Here we're at 0
![elevation0](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/7174039/45ef32b2-bc10-479e-8e86-571fc7f785f0)
If I zoom in more, elevation goes back up but in reality it's after passing below 0
![elevationBelow0](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/7174039/d689892a-ff15-4ae5-b085-e7d049e24232)
So I guess something about elevation is wrong and need to be adjusted. 
I'll try to think about something.

**Comment by gkjohnson** [comment]
> Normally it's accounting for the furthest distance possible in all direction from the given coordinates.

Cool I was going to say this is what we should do.

> For this particularly extreme case it's mostly because the elevation goes close to 0 while we're still above ground.

Oh okay I think I see what's happening now. The horizon distance at sea level (0) would be zero, but because the earth tiles do not seem to line up perfectly with the WGS84 ellipsoid and / or there are valleys below sea level we're compute a closer value than is representative for the real loaded geometry.

I'm wondering if taking the max value between the distance to the WGS84 ellipsoid and height above terrain to represent sea level is the right thing to do here?

**Comment by AlaricBaraou** [comment]
> The horizon distance at sea level (0) would be zero, but because the earth tiles do not seem to line up perfectly with the WGS84 ellipsoid and / or there are valleys below sea level we're compute a closer value than is representative for the real loaded geometry.

That's my feeling too.

> I'm wondering if taking the max value between the distance to the WGS84 ellipsoid and height above terrain to represent sea level is the right thing to do here?

I guess it would improve things, but while thinking about other issues I started to consider things that should be visible because they're above the horizon surface ( very tall building / moutain ) that are discarded by the current method.
See here how Mt Everest slowly disappear as I get closer to the sea level. ( view from #26.5261,87.0570,1680.1134 )

https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/7174039/e1e9bbe2-7226-4fb7-9bda-20470ae4db04

To solve this, I believe the simplest way is adding 8,848 meters ( highest point on earth from see level ) to the current elevation to guarantee seeing any high landmark in the horizon from see level.

Pros: This also solve the above issue.
Cons: In most areas of earth, there isn't a need for this offset and it would result in a larger Frustum than needed.

**Comment by gkjohnson** [comment]
> To solve this, I believe the simplest way is adding 8,848 meters ( highest point on earth from see level ) to the current elevation to guarantee seeing any high landmark in the horizon from see level.

I think this would solve the issue but you're right I think it's generally not needed in most cases and would expand the frustum quite a bit. The primary issue is that as the elevation approaches 0 so does the far clip plane. I think it would be best to have a _minimum_ altitude we use for calculations - the question is just how do we pick that value. 

8848 might be an okay choice but it increases the far clip distance _significantly_. The difference in computed horizon distance between 10 m above the ground and 8848 m is ~11000 m vs ~335000 m or 30 times which is a lot. Measuring the altitude above the geometry might be the best way to fix this (without fixing something like the mountains disappearing over at the horizon) but it may be expensive to determine the height with an additional raycast unless we can reuse a previous one. I'd have to check the code but a smaller, fixed minimum value may be just fine, though.

**Comment by AlaricBaraou** [comment]
> but it may be expensive to determine the height with an additional raycast unless we can reuse a previous one

Just a though about using a previous raycast hit, I believe they're done against any element in the scene, so on top of some building, house or anything it will return a smaller value than what we'd prefer or create a shifting horizon when moving above elements of various heights. 
Though it might never happen if we consider that the current issue only happen on very "low places"

>  fixed minimum value may be just fine, though.

That sounds safe and easy

**Comment by gkjohnson** [comment]
That's a good point 🤔 Perhaps a hard coded "MINIMUM_ELEVATION" value would be best for now.

Also I've created #507. It seems a bit related - while testing this it's become clear that this function doesn't provide a negative elevation value the way we'd expect leading to some of this odd frustum behavior below sea level.
