### ISSUE TITLE
Introduce Foveated Rendering - prioritizes tiles in the center of the screen

### ISSUE THREAD

**Issue by jo-chemla** [NASA-AMMOS/3DTilesRendererJS#496]
The CesiumJS library supports foveated rendering feature - see [these params](https://cesium.com/learn/cesiumjs/ref-doc/Cesium3DTileset.html#foveatedConeSize) in their doc - which uses a parametrized cone to prioritize the fetching of tiles closest to the center of the screen. This helps ensure the best quality is achieved faster in the region of interest of the viewport, closer to the center of the screen. 

This seem to be the [portion](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/Cesium3DTile.js#L854-L891) of their implementation in the cesiumjs lib. They are artificially increasing the screenSpaceErrors of tiles farther from that viewing cone, in order to de-prioritize them from the queue. 

Might be interesting to add that feature to 3DTilesRendererJS in case you think it's worth it - otherwise, don't hesitate to close!

**Comment by gkjohnson** [comment]
Issue #424 describes something similar. If you'd like to make a PR or something I'd be open to supporting this. We'd need a separate error metric on the tile that scales based based on distance to the center of the screen so it can be used to sort the tiles in the download and parse queue "priority callback". Adding something like a "load order" visualization to the DebugTilesRenderer would be helpful for understanding the impact of this kind of change, as well

Also note that recent changes to the renderer should have made the Google Earth tiles load in much faster since far fewer are being loaded (see #483).

**Comment by jo-chemla** [comment]
Oops sorry, don't know how I've missed the original issue thread, that's indeed exactly that idea and cesium source. Closing in favor of #424 

And great to see google 3d-tiles loads twice as less tiles with the updated far frustum on the horizon!
