### ISSUE TITLE
Why only load JSON without loading any model files?

### ISSUE THREAD

**Issue by bbhxwl** [NASA-AMMOS/3DTilesRendererJS#544]
Why only load JSON without loading any model files?

```ts
<script setup lang="ts">
import * as THREE from "three"
import {PerspectiveCamera, Scene, WebGLRenderer} from "three";
//定义拖动旋转
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js"
import { TilesRenderer } from '3d-tiles-renderer';
let tilesRenderer:any;
let scene:Scene;
let camera:PerspectiveCamera;
let renderer:WebGLRenderer;
let controls:OrbitControls;

const div=ref<HTMLElement>()

function renderLoop() {
  controls.update()
  tilesRenderer.update();
  renderer.render( scene, camera );
  requestAnimationFrame(renderLoop);
}
onMounted(()=>{
  if(!div.value)return
  scene= new THREE.Scene();
  console.log(div.value?.offsetHeight)
  camera=new THREE.PerspectiveCamera(75,div.value?.offsetWidth/div.value?.offsetHeight,0.1,1000);
  renderer = new THREE.WebGLRenderer();
  renderer.setSize(div.value.clientWidth, div.value.clientHeight);
  div.value.appendChild(renderer.domElement);
  controls = new OrbitControls(camera, renderer.domElement);
  camera.position.z = 5;
  camera.position.y = 5;
  tilesRenderer = new TilesRenderer( './tileset.json' );
  tilesRenderer.setCamera( camera );
  tilesRenderer.setResolutionFromRenderer( camera, renderer );
  scene.add( tilesRenderer.group );
  renderLoop();

})
</script>

<template>
<div class="w-full h-full" ref="div"></div>
</template>

<style scoped>

</style>
```
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/26525599/0f3fa400-5e03-4a8b-b1d7-bf2df32d4ba4)

**Comment by gkjohnson** [comment]
Again, without the model itself I can only guess at what the issue is. It could be that the model is significantly offset from the center of the scene in which case you'll have to position the tileset based on that position.

You can get and log the bounding sphere using the [getBoundingSphere](https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#getboundingsphere) function to see if this might be the issue.

**Comment by bbhxwl** [comment]
> Again, without the model itself I can only guess at what the issue is. It could be that the model is significantly offset from the center of the scene in which case you'll have to position the tileset based on that position.
> 
> You can get and log the bounding sphere using the [getBoundingSphere](https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#getboundingsphere) function to see if this might be the issue.

<img width="721" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/26525599/de5e61c9-26ed-4553-9f1a-23610bfe9d14">

**Comment by bbhxwl** [comment]
> Again, without the model itself I can only guess at what the issue is. It could be that the model is significantly offset from the center of the scene in which case you'll have to position the tileset based on that position.
> 
> You can get and log the bounding sphere using the [getBoundingSphere](https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#getboundingsphere) function to see if this might be the issue.

    tilesRenderer.group.position.copy( sphere.center ).multiplyScalar( - 1 );
Thank you, it can be displayed now.

**Comment by bbhxwl** [comment]
Maybe the default origin of the model is too far to see

**Comment by bbhxwl** [comment]
> Again, without the model itself I can only guess at what the issue is. It could be that the model is significantly offset from the center of the scene in which case you'll have to position the tileset based on that position.
> 
> You can get and log the bounding sphere using the [getBoundingSphere](https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#getboundingsphere) function to see if this might be the issue.

Why is it that there is no need to adjust the position in cesium? After adjusting the position of the code like this, the angle of the model also changes a bit. Is it not fully compatible with the Cesium coordinates?

**Comment by gkjohnson** [comment]
> Why is it that there is no need to adjust the position in cesium?

Cesium operates in the the earth coordinate frame (WGS84) so the 3d tiles file you are providing is likely a distance of the radius of the earth away from the origin. When visualized with something like the globe tile sets it will be correctly positioned. This project is otherwise unopinionated about how tiles are rendered so if a user wants the model centered they must do so themselves.

**Comment by bbhxwl** [comment]
> > Why is it that there is no need to adjust the position in cesium?
> 
> Cesium operates in the the earth coordinate frame (WGS84) so the 3d tiles file you are providing is likely a distance of the radius of the earth away from the origin. When visualized with something like the globe tile sets it will be correctly positioned. This project is otherwise unopinionated about how tiles are rendered so if a user wants the model centered they must do so themselves.

But after I set it up, the model seems to be tilted and angled, I don't know why? Is there any tool that can export FBX files to 3D tiles? Tools that support LOD? And is there no problem using it in 3DFilesRenderJS?

**Comment by gkjohnson** [comment]
> But after I set it up, the model seems to be tilted and angled, I don't know why?

Again, this is because the model is specified in the WGS84 coordinate frame. If the model is positioned on the south pole, for example, it will be "upside down" compared to three.js' coordinate frame. You'll have to rotate it yourself based on the assumed orientation relative to the planet.

You can see how that's done in the "Cesium Ion" example [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/37a4264d2392515cd37ecb5f7cf7d26b8ac336f5/example/ionExample.js#L73-L90).

> Is there any tool that can export FBX files to 3D tiles

None I'm familiar with
