### ISSUE TITLE
Bug: DOMException: signal is aborted without reason

### ISSUE THREAD

**Issue by Nmzik** [NASA-AMMOS/3DTilesRendererJS#561]
I've encountered a bug related to external tilesets. It appears that the tile somehow was aborted before. However, I have no idea how that's possible, considering an AbortController instance is created per each load. Therefore, at this point, I need to check additionally if the signal was aborted before (`signal.aborted`). It seems to happen randomly (but only if you have externals tilesets defined in the main Tileset.json).

![Screenshot 2024-05-20 143649](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/691945/0f000d35-7727-4553-b7d0-51ff64c346a4)

![Screenshot 2024-05-20 144303](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/691945/5aded8a2-0c70-4157-81d4-38f26a441c06)

```
{
    "stack": "Error: signal is aborted without reason\n    at http://localhost:3000/node_modules/3d-tiles-renderer/src/base/TilesRendererBase.js?v=02784ebd:439:19\n    at LRUCache.unloadUnusedContent (http://localhost:3000/node_modules/3d-tiles-renderer/src/utilities/LRUCache.js?v=02784ebd:162:26)\n    at http://localhost:3000/node_modules/3d-tiles-renderer/src/utilities/LRUCache.js?v=02784ebd:180:10"
}
```

**Update:** I'm unable to check the status of the variable `signal.aborted`
```
if (t.__loadAbort.signal.aborted === false)
   t.__loadAbort.abort(); //Bypasses the if statement and throws an exception. What's going on?
```

**Comment by gkjohnson** [comment]
Aborting tilesets and tiles is done when the tile cache is full and a tile that has started loading is no longer needed - so aborting is correct. This isn't a bug in the sense that it will cause any problems but I agree the log is not desired. It looks like the thrown abort signal error isn't being caught in one of the fetch promises causing it to log.

If you'd like to investigate and make a PR I'm happy to review it and get it merged. Otherwise I'll have to take a look when I get a chance.

**Comment by gkjohnson** [comment]
I just look a brief look at the TilesRenderer class and it's possible that this is the promise path where the abort is not getting caught: https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/TilesRenderer.js#L341-L363

It's possible that just adding an empty "catch" statement to that promise chain will prevent the log if you'd like to give that a try.
