### ISSUE TITLE
Add support for external tilesets

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#62]
See example tileset here:

https://github.com/CesiumGS/3d-tiles-samples/tree/master/tilesets/TilesetWithRequestVolume

**Comment by liberostelios** [comment]
We are interested in this feature, as we now have a pretty big `tileset.json` file of a couple dozens MBs. I've been thinking about it, but it feels that it's not that trivial to implement since the traversal of the tiles assumes a fixed tree.

The most straightforward approach I could think of is to mark tiles with external references as "to be downloaded" during the traversal (assuming their error is appropriate) and then initiate their fetching after that traversal. So, when they become available, those leaf tiles could be replaced by the external file's tree. After that, the traversal would deal with them as if they were original on the same tileset file.

What do you think?

**Comment by gkjohnson** [comment]
That would be great if you would like to take this on!

> The most straightforward approach I could think of is to mark tiles with external references as "to be downloaded" during the traversal (assuming their error is appropriate) and then initiate their fetching after that traversal. So, when they become available, those leaf tiles could be replaced by the external file's tree. After that, the traversal would deal with them as if they were original on the same tileset file.

This is how I've been imagining this being implemented and I think keeps everything simple overall. I don't think we need to wait until the end of the traversal to start the fetch, though -- we can just start the tileset download like when [we do for geometric tiles](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/base/traverseFunctions.js#L302-L306) but have a special case for .json files so it loads the tilset root and sets it as a child.

A bonus would be tracking the tile with the external tileset content in the LRUCache so we can unload if it hasn't been traversed in awhile. But maybe that can come later.

I think we'll want a simple test case to run for this, as well. Cesium provides this relatively shallow example with an external tileset so may be we can use this when running manual tests: https://github.com/CesiumGS/3d-tiles-samples/blob/master/tilesets/TilesetWithRequestVolume/tileset.json

Thanks for looking into this!
