### ISSUE TITLE
Incorrect distance calculation for OBB

### ISSUE THREAD

**Issue by Desplandis** [NASA-AMMOS/3DTilesRendererJS#622]
### Describe the bug

The `TileBoundingVolume` module assumes that the `transform` matrix does not contain a scale component. This is incorrect since it is calculated from `tile.transform` and breaks both distance and SSE calculations of tiles using non-identity scaling.

### Code

The following code is no longer valid with non-identity scaling:
https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/c076d8b1de7cfb06881393c6c7c2a472abd10d9e/src/three/math/TileBoundingVolume.js#L118-L120

I'll push a PR to fix this issue, but is there a reason why you're not using `three.js` `OBB`?

**Comment by gkjohnson** [comment]
Thanks - appreciate having more eyes on this stuff. I'll take a deeper look at the PR soon.

> is there a reason why you're not using three.js OBB?

When the project started the three.js OBB class didn't exist (or I didn't know of it, at least) and custom functional implementations were written. In a previous version of tiles renderer all the cached OBB transforms etc were stored on the tile object with the tile transform and obb transform likely being applied separately, which is probably where this comment came from. This bug probably appeared when migrating the logic to a class and premultiplying the tile transform in.

Admittedly it's maybe a bit odd that the OBB class can store a bounding box with an off-axis, non-uniform scale. All the bounding volumes shapes in the `TileBoundingVolume` were designed to have the tile transform pre-multiplied in for the sake of speed and avoiding an extra matrix multiplication per tile but it may be less intuitive. And in the case of non uniform tile scale the bounding sphere will wind up being larger than necessary, though I'm not sure how common that use case is. But this is something that can be reconsidered another time if needed.

Regarding other implementation details on OBB - a lot of extra information is cached (OBB planes, points, inverse transform) to avoid recalculating them every time they're needed since things like frustum intersection checks happen frequently. Likewise the frustum intersection function is a modified implementation since three.js' AABB implementation provides false positives (see https://github.com/mrdoob/three.js/issues/27756)
