### ISSUE TITLE
Deprecation of `BatchTable#getData`

### ISSUE THREAD

**Issue by Desplandis** [NASA-AMMOS/3DTilesRendererJS#657]
**Describe the bug**

The latest release and PR #627 deprecates the method `getData` of `BatchTable`.
We could be however want to retrieve a whole named buffer. Some of the use-cases includes the fact that we could want to generate a specific VBO (e.g. `color`) from an entry of the batch table. This is our case with `py3dtiles` which generates 3D Tiles point clouds from LAS and encode the `classification` property in the batch table, we then use this data to color our point cloud.

**Comment by gkjohnson** [comment]
We can add it back if it's needed but I think the name should be changed to better reflect what's being retrieved - like `getBuffer` or `getPropertyBuffer` or something.

**Comment by woondossier** [comment]
This will also cause issues for the Dutch 3D BAG implementation, the batchtable includes an attributes entry with info about the building based on batch id index so we get that by using .getData("attributes") and then use that data to display building information.

So basically without this function, we can't update anymore because it breaks existing functionality. So if it could be brought back under a different name it would be greatly appreciated.

The company that creates these datasets also has an [viewer](https://3dbag.nl/en/viewer) that shows this as well 
[Sourcecode](https://github.com/3DBAG/3dbag-viewer/blob/2317b9a3710e7dce692b0af825b8f5ee35ca814d/src/components/ThreeViewer.vue#L904) showing the function

**Comment by gkjohnson** [comment]
> So basically without this function, we can't update anymore because it breaks existing functionality.

Can you explain why the newly added `getDataFromId` in #627 does not work for your use case? It provides all attributes associated with an id:

```js
const attributes = JSON.parse( batchTable. getDataFromId( batch_id ).attributes );
```

**Comment by woondossier** [comment]
Ah yes, that specific use case would work, and I actually agree it's an improvement. 

The main issue that I'm running into is that we allow people to "delete" buildings from the tiles for urban planning purposes and when a tile is loaded we loop through the attributes and check if a identifier is in the list of deleted buildings and "remove" it from the tile based on the index. 

This is done in reverse order because there's no ID yet as these change with every release of a new dataset, so we store the unique identifier instead, so I suppose the real issue is we do attributes array -> id instead of id -> attributes in this particular case.

So if there is a way of getting all the IDs of a BatchTable, it would also solve the issue I'm having right now but I couldn't find it.

**Comment by gkjohnson** [comment]
You can still iterate over all ids in the BatchTable with this function and check the deletion state:

```js
let target = {};
for ( let i = 0; i < batchTable.batchSize; i ++ ) {

  if ( batchTable.getDataFromId( i, target ).isDeleted ) {
    
    // delete the building
    
  }

}
```

I see this `batchSize` field isn't specified in the d.ts file, though, so we can add that in the next release.

**Comment by jailln** [comment]
> We can add it back if it's needed but I think the name should be changed to better reflect what's being retrieved - like `getBuffer` or `getPropertyBuffer` or something.

I'd like to push a PR to add it back for the reason explained by @Desplandis. Do you have any preferences about the name or should I stick with `getData` ? There is already a `getBuffer` method in `FeatureTable` which does different things, I think using this name would be confusing. Personally I would stick with `getData` but if we want to change we may change it to `getProperty` or `getPropertyData` ?

**Comment by gkjohnson** [comment]
To be clear - you're using the typed array / array buffer directly to initialize a vertex buffer? Is that why iterating over all the elements (as in https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/657#issuecomment-2277772252) won't work? Assuming it won't we can merge a PR that adds the functionality back.

My concern with `getData` is that it will return an array of data for a single property while `getDataForId` will return a object definition of all properties for an id rather than just for a single property as the common naming between the functions might imply. I think that difference is a bit confusing. I think something like `getPropertyArray( key )` is more descriptive of what is returned.

**Comment by jailln** [comment]
> To be clear - you're using the typed array / array buffer directly to initialize a vertex buffer? Is that why iterating over all the elements (as in [#657 (comment)](https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/657#issuecomment-2277772252)) won't work? Assuming it won't we can merge a PR that adds the functionality back.

Yes that's it - see [here](https://github.com/iTowns/itowns/blob/master/src/Layer/OGC3DTilesLayer.js#L297-L302)

> My concern with `getData` is that it will return an array of data for a single property while `getDataForId` will return a object definition of all properties for an id rather than just for a single property as the common naming between the functions might imply. I think that difference is a bit confusing. I think something like `getPropertyArray( key )` is more descriptive of what is returned.

You're right, `getPropertyArray( key )` is clearer, thanks. I'll open a PR.

**Comment by jailln** [comment]
@gkjohnson can you close this issue please? (I don't have the rights to do so)
