### ISSUE TITLE
CMPT issue with i3dm

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#681]
**Describe the bug**

When loading a cmpt with i3dm data, all the 3d instances are merged, their positions are wrong.
I've also added the rtc_center https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/680. 
Do you have an idea that could help me ?
Thank you 

**To Reproduce**

1. Use the modifications from https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/680
2. Load the tileset containing a cmpt with i3dm data. For example from TOULOUSE METROPOLE : https://github.com/AnthonyGlt/3DTilesRendererJS/tree/i3dm/example/arbres_rieux_cmpt_sample
3. All the 3d models are at the same location

**Screenshots**

Expected (from cesium):
![Screenshot from 2024-08-08 12-16-40](https://github.com/user-attachments/assets/2e379ede-a966-4637-a720-0e877cf482fb)

Result:

![Screenshot from 2024-08-08 12-16-57](https://github.com/user-attachments/assets/7b998b0a-2c1e-43ae-9f29-c21c3e06b898)

**Comment by gkjohnson** [comment]
I'm seeing that [this file](https://raw.githack.com/AnthonyGlt/3DTilesRendererJS/raw/i3dm/example/arbres_rieux_cmpt_sample/content/0_0_0.cmpt) can't load at all due `byteLength` containing an invalid value:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/787e20b6-8928-4517-8dec-b0c957c60229">

How are you loading this?

**Comment by AnthonyGlt** [comment]
Sorry about that, should  be good now.
Thank you

**Comment by gkjohnson** [comment]
It looks like this is an issue with how the I3DMLoader processes the gltf into instances. The first i3dm file nests both the meshes to instance in different parents with different scales. It seems like these scales should be applied before the instance transformation but they're currently applied after due to I3DMLoader converts meshes to instanced meshes (the meshes are directly replaced with instanced meshes [under the same parent](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/e6ab1c65deb2c916032f3fd8f7671debdf719792/src/three/loaders/I3DMLoader.js#L99-L113)).

I guess the right way to this would be to use the hierarchy provided by the glTF to compute the matrix world transforms of the loaded meshes and then include those transforms in the instance mesh matrices. Then the returned scene object can just be a flat list of the InstancedMeshes and the hierarchy can otherwise be thrown out. This _should_ result in a scene that looks like that same glTF model has been loaded many times, which makes more sense as the behavior for the I3DM loader, I think.
