### ISSUE TITLE
Testing maxByteSize does not work

### ISSUE THREAD

**Issue by zysyz** [NASA-AMMOS/3DTilesRendererJS#738]
I first tested the TileCompressionPlugin plugin and found that there was indeed a loss in model quality, but the memory usage did not decrease.
Then I tested maxByteSize, and no matter how much the value was adjusted, I did not find any changes in the memory usage. May I ask if my code was written incorrectly or if there are any other issues.Here is a partial code of mine:

```
import { TileCompressionPlugin } from './ TileCompressionPlugin.js'
const tilesRenderer = new TilesRenderer( './ model/tileset.json' ); 
……
tilesRenderer.registerPlugin( new TileCompressionPlugin() );

tilesRenderer.fetchOptions.mode = 'cors';
tilesRenderer.manager.addHandler(  /\. (gltf|glb)$/g, loader );
tilesRenderer.setCamera( camera );
tilesRenderer.setResolutionFromRenderer( camera, renderer );

tilesRenderer.errorTarget = 35;
tilesRenderer.lruCache.maxByteSize = 0.3 * 2**30;
tilesRenderer.lruCache.minByteSize = 0.2 * 2**30;
```

**Comment by gkjohnson** [comment]
> there was indeed a loss in model quality

Can you provide some screenshots showing the loss in model quality? It's not unexpected and it will impact different models with different severity but it's good to get a sense of how affected different tile sets are.

> but the memory usage did not decrease.

How are you measuring this? The GPU memory will be what's affected impacted due to removing mip maps. Measuring memory usage differences using any CPU profiling tools will likely not show much difference.

**Comment by zysyz** [comment]
> 你能提供一些屏幕截图显示模型质量的损失吗？这并不意外，它会对不同的模型产生不同的严重程度的影响，但最好了解不同的瓷砖集受到的影响程度。

The following is a comparison of the border of a billboard before and after using tilesRendering. registrant Plugin (new TileCompression Plugin ()).
![17d03ccc-2795-4232-b3e4-6e2a5d6b626e](https://github.com/user-attachments/assets/aadff78e-24a1-4fd6-9e5e-d5a0c27650d5)
![a33786b4-b20b-4553-aff3-5a377511908f](https://github.com/user-attachments/assets/886897fd-4657-443f-967a-3c344f889c05)



> How are you measuring this? The GPU memory will be what's affected impacted due to removing mip maps. Measuring memory usage differences using any CPU profiling tools will likely not show much difference.

I checked the GPU memory usage in the task manager.

Also, do you know what happened when maxByteSize didn't work

**Comment by gkjohnson** [comment]
> The following is a comparison of the border of a billboard before and after using tilesRendering.

This looks like artifacts that are a result of overly aggressive UV compression (ie 32 bit to 8 bit). You can try adjusting this to Int16Array or Uint8Array to see if it helps. Perhaps the default for the plugin could be adjusted, as well.

> I checked the GPU memory usage in the task manager.

I'm not sure of how precise these tools are. The plugin shrinks the vertex buffer precision resulting in a smaller buffer and disables mip map generation in three.js which otherwise requires more GPU memory.

**Comment by zysyz** [comment]
> I'm not sure what you mean by this. What's not working? There is a bug I'm currently fixing with this flag in #727 which is causing too much data to unload if the max bytes cap is reached.

Regardless of whether I set tilesRendering. lruCache. maxByteSize=0.3 * 2 * * 30 or tilesRendering. lruCache. maxByteSize=0.0003 * 2 * * 30, the memory usage remains the same

**Comment by gkjohnson** [comment]
> maxByteSize

Looks like there was a typo in the documentation. The correct key is `maxBytesSize`. I've adjusted the docs - though keep in mind there's a bug that still needs to be fixed with the setting.

**Comment by zysyz** [comment]
> > maxByteSize
> 
> Looks like there was a typo in the documentation. The correct key is `maxBytesSize`. I've adjusted the docs - though keep in mind there's a bug that still needs to be fixed with the setting.看起来文档中有一个错字。正确的键是`maxBytesSize`。我已经调整了文档-虽然请记住，有一个错误，仍然需要修复的设置。

I tested it and found that after changing maxByteSize to maxBytesSize, the effect is still the same as before, regardless of the value, the memory usage remains unchanged

**Comment by gkjohnson** [comment]
Again, I can't speak for the tools you're using to measure memory usage but setting the `maxBytesSize` field to a low value causes fewer tiles (you can check the LoDs loaded visually and in the network tab). If the tools you're using are not reflecting this difference then there must be an issue with the way the memory is being measured.

**Comment by jailln** [comment]
I encountered the same issue. It probably happens because you use `3DTilesRendererJS` in a project with `three < 0.166.0` which results in `TextureUtils` being undefined [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/9b90ed0a53d216771a500a5ae0019cb7b6b1ebe7/src/three/utilities.js#L9) and therefore in `LruCache.cachedBytes` never being computed.

@gkjohnson I think we should at least add a warning [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/9b90ed0a53d216771a500a5ae0019cb7b6b1ebe7/src/three/utilities.js#L9) and specify in the doc that `lruCache.minBytesSize` and `lruCache.maxBytesSize` only work with `three >= 0.166.0` or update three peer-dependency to `^0.166.0`. What do you think is best?

**Comment by gkjohnson** [comment]
> @gkjohnson I think we should at least add a warning [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/9b90ed0a53d216771a500a5ae0019cb7b6b1ebe7/src/three/utilities.js#L9) and specify in the doc that lruCache.minBytesSize and lruCache.maxBytesSize only work with three >= 0.166.0 or update three peer-dependency to ^0.166.0. What do you think is best?

Lets update the docs, for now, to specify that it only works in higher versions of three.js. In the coming months I'll plan to make the [v0.4.0](https://github.com/NASA-AMMOS/3DTilesRendererJS/milestone/37) release which will have a number of breaking changes including bumping the three.js version to >= 166 (see #549). It's probably worth updating the "Question" issue template to include a request for project and three.js version numbers so these kinds of version-specific problems are more clear if you'd like to make that change, as well.
