### ISSUE TITLE
Understanding elevation (Google 3D Tiles)

### ISSUE THREAD

**Issue by RodrigoHamuy** [NASA-AMMOS/3DTilesRendererJS#748]
Example: Trafalgar Square ( `tiles.setLatLonToYUp(51.507500 * MathUtils.DEG2RAD, -0.128100 * MathUtils.DEG2RAD);` )

- In `3DTilesRendererJS` elevation seems to be roughly at ~ 55 meters.

```js
const axes = new AxesHelper(1000);
axes.position.y = 55;
scene.add(axes);
```

![image](https://github.com/user-attachments/assets/63cae96a-6918-430e-8826-e529874bfb9a)

- whatismyelevation.com says is ~14 meters: https://whatismyelevation.com/location/51.50804,-0.12806/Trafalgar-Square--9-Bedford-Ct--London--WC2E-9LU--England-
- Google Earth says ~8 meters (bottom right corner): https://earth.google.com/web/search/Trafalgar+Square,+Trafalgar+Square,+London/@51.50777626,-0.12779714,8.39731919a,220.41331458d,35y,0h,0t,0r/data=CpkBGmsSZQolMHg0ODc2MDRjZTM5NDFlYjFmOjB4MWE1MzQyZmRmMDg5YzYyNxnYCwVsB8FJQCGA0lCjkGTAvyoqVHJhZmFsZ2FyIFNxdWFyZSwgVHJhZmFsZ2FyIFNxdWFyZSwgTG9uZG9uGAIgASImCiQJPMqZBetpNUARO8qZBetpNcAZwjOMbTxvRkAhpXzZeRxNTcBCAggBOgMKATA

Any reason why Google 3D tiles seem so off? 

Thanks!

**Comment by gkjohnson** [comment]
My only explanation is that Google's data isn't completely precise compared to what are considered canonical altitudes. I [asked a similar question on the Cesium forums](https://community.cesium.com/t/how-accurate-are-google-photorealistic-3d-tiles-altitudes/30155) but never got an answer. Basically Mt Everest's height is measured to be [8,848 meters](https://oceanservice.noaa.gov/facts/highestpoint.html) but when measuring against the served data in this library and Google Earth we get values around 8,700 meters (~8,700m and 8,729m respectively, see images in forum post). It's possible the discrepancy between this project and the Google Earth app is caused by different level of details being loaded (see #747) but I can't be sure.

@lilleyse sorry to ping again - I'm not sure if you have any more information on the precision of Googles Tiles. I see there's no information regarding error bounds listed in the Cesium Ion page. The [page on Cesium's globe tiles data](https://cesium.com/platform/cesium-ion/content/cesium-world-terrain/) has _more_ information on resolution but doesn't state anything about resolution or accuracy relating to altitude. It would nice if this were listed for the data if available - and noted if it's not known.

**Comment by lilleyse** [comment]
We've noticed elevation discrepancies with Google 3D Tiles as well. We don't have specific details aside from Google's disclaimer [here](https://mapsplatform.google.com/resources/blog/commonly-asked-questions-about-our-recently-launched-photorealistic-3d-tiles/) (see "Can I use it for precise measurements? Can I get the elevation info or other attribution?")

**Comment by gkjohnson** [comment]
Thanks @lilleyse - is there any more information about altitude information for Cesium's quantized mesh globe tiles? Should we expect that tile set to be more precise? The page I linked looks like it only specifies resolution in latitude and longitude.

**Comment by gkjohnson** [comment]
I've created a forum post [here](https://community.cesium.com/t/how-to-retrieve-globe-altitude-at-lat-lon-in-cesium/35332) to see what the right way is to measure heights in Cesium to get a sense for accuracy since it wasn't obvious how to do so. If there's any broader information on elevation accuracy in the Cesium globe data sets that would be best, though!

**Comment by lilleyse** [comment]
@gkjohnson Cesium World Terrain should be more precise. If the input data has an embedded vertical datum we use that, otherwise we default to EGM2008. (Though I think the current version of CWT defaulted to EGM96).

**Comment by gkjohnson** [comment]
Thanks @lilleyse - I've extracted the geoid height from [this site](https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html) and it looks like it adds an additional `28.34m` to the mt everest height - bringing the Cesium terrain height to ~8,800m and the Google Terrain sample from this project to ~8,730m.

Looking at the data from Trafalgar Square it looks like the geoid difference is around -46m. Cesium's height sample at the provided lat / lon is ~55m, as well, so with the geoid difference both samples are ~8m, matching Google Earths. It's possible that Google Earth is already including this difference in the calculations.

Other than that I can't tell you why the reported heights in the "whatismyelevation" page. It only really talks about taking data from your mobile device to derive height but not where it comes from when you manually enter a location. Without knowing the provenance of the data being sampled in any of these data sets it's not possible to say what kind of inaccuracies might be introduced and where. Also it's worth nothing that the linked elevation website [reports "8,730m" when querying the coordinates for Mt Everest](https://whatismyelevation.com/location/27.9881,86.9250) so I wouldn't necessarily consider it a perfect source of truth for this, either.

**Comment by gkjohnson** [comment]
I think this has been answered as well as it can be. The Cesium data may be more accurate but without more information about the datasets and processing used it won't be possible to charactararize the error of the terrain.
