### ISSUE TITLE
[Question] generate 3tiles from gltf or BufferGeometry

### ISSUE THREAD

**Issue by arpu** [NASA-AMMOS/3DTilesRendererJS#76]
Hello

what are the best options today to generate this 3dtiles from a gltf/glb model file or pur threejs BufferGeometry?

**Comment by gkjohnson** [comment]
Hey @arpu!

Internally we use a custom pipeline with some more proprietary processes for the types of data we work with so I'm less familiar with the typical way to generate tilesets. I did come across [this repo](https://github.com/CesiumGS/3d-tiles-validator/tree/master/tools) which looks like a now-defunct set of tools from Cesium for helping to generate 3d tiles. I haven't used it myself but it may be a good place to start.

From [this page in the Cesium docs](https://cesium.com/docs/on-premise/tilers/3d-buildings/) it looks like they've moved to a service model for using the Cesium generation pipeline. There may be other open source projects I'm unaware of, though.

**Comment by arpu** [comment]
Hey @gkjohnson,

thx a lot for the Information will try the Cesium 3d-tiles-validator and report back

**Comment by arpu** [comment]
to you think today the 3dtiles is the best format/option for big landscapes?

**Comment by gkjohnson** [comment]
> thx a lot for the Information will try the Cesium 3d-tiles-validator and report back

That would be great -- if it looks promising I wouldn't mind including some information on how to generate tiles in this repo.

> to you think today the 3dtiles is the best format/option for big landscapes?

Many games use something like a quad tree to do frustum culling or level of detail on tiles of terrain but I'm not aware of another standardized format used to represent this information. 3d Tiles is a bit more flexible than a quad tree because it supports arbitrary bounds and placement of children so you might be able to write something more specific and a bit faster depending on your data and use case. That would involve writing your own quad tree and your own format, though (unless there's another open source project that supports that already).

**Comment by gkjohnson** [comment]
@arpu from a discussion in #77 it looks like the [pg2b3dm](https://github.com/Geodan/pg2b3dm) can convert PostGIS data to 3d tiles. It's different than the type of data it sounds like you want to convert but maybe something there is helpful.

**Comment by gkjohnson** [comment]
It looks like there are a number of converters for different file formats listed in the [3dtiles tag on Github](https://github.com/topics/3dtiles).
