### ISSUE TITLE
[REGRESSION] Tiles aren't made visible after sorting

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#767]
The tiles are downloaded and loaded but not displayed.
It seems that the issue appeared after this [MR](https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/723) 
Exactly this line:
https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/819c0580c2b4826dc1dfa4972d6bb52a0c65b5f4/src/base/TilesRendererBase.js#L239

**To Reproduce**

1. Load this tileset https://storage.googleapis.com/ahp-research/maquette/ign/buildings/beta.3/1.0/tileset.json
2. Use this scale: `		geospatialRotationParent.scale.set( 0.01, 0.01, 0.01 );` (big model)
3. Set the `errorTarget` to zero

**Screenshots**

Without the sorting line:
![image](https://github.com/user-attachments/assets/1b099a16-e48b-4f6b-830d-5ba168e6ef2f)

With the sorting line:
![image](https://github.com/user-attachments/assets/68d5c59b-1e1d-48d6-9662-a19f40f37283)

It's again for a specific tileset :grimacing: 

I've tried to increase the cache size, without luck
`tiles.lruCache.maxBytesSize =  2**30;`

Thank you

**Comment by gkjohnson** [comment]
I've already described the issue with this tile set in https://github.com/iTowns/itowns/issues/2335, I think. The newer tile set in https://github.com/iTowns/itowns/issues/2335#issuecomment-2330159561 works better but since the "ADD" refinement is used but these data sets still more or less have no hierarchy to them. The root node has over 28,000 children, over 14,000 of which are external tile sets with the same very large "geometricError" value (~1000) while the root node has an even larger geometric error value (~111,111) meaning that every child will basically load / render as soon as that root tiles error value is met.

The tile set is more or less structured so it's just loading everything in the frustum, leading to cases like this with over 3000 nodes rendering and 8000 nodes loaded including external tile sets (lru cache max size was increased to 10,000 items and max bytes was increased to over 3GB):

<img width="300" alt="image" src="https://github.com/user-attachments/assets/ee0c0977-f9bb-4e05-8777-a348544c8c37">

There are still more tiles that would load if I increased the max bytes size. Basically this tile set isn't really taking advantage of how 3d tiles is supposed to work. There should be a lot more hierarchy (something like a quad tree with 4 children per tile) with progressively decreasing geometric error which will act as screenspace error cutoffs for when the next set of additive tiles should be rendered.

Also keep in mind that if a parent tile's error threshold is met then _all_ children must be checked for frustum intersections. That means that at least 28,000 region-frustum checks must be done every frame which is going to have a significant impact on framerate alone. This is another reason to use a more well-structured hierarchy.
