### ISSUE TITLE
Revit file to 3Dtile  open erro

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#879]
**Describe the bug**
I exported the Revit file to 3Dtile (3Dtile 1.1 standard, Meshopt compression), which can be loaded normally in Cesium, but in 3Dtilerender, it either cannot be loaded or the model loses objects after loading. I provide the 3Dtile model and hope to get help. Thank you。

**Screenshots**
![image](https://github.com/user-attachments/assets/3537c067-5b93-4f1c-ab6c-7dc55e06ef51)
![image](https://github.com/user-attachments/assets/730c0478-3d69-4d69-9358-5b43e6207ed6)

[dtz2.zip](https://github.com/user-attachments/files/18196741/dtz2.zip)

**Comment by gkjohnson** [comment]
Thank you for the test model. Looks like the tile GLB files are improperly formed or there's a bug in three.js' GLTFLoader - I'm seeing the following errors when loading the model:

```
RangeError: Invalid typed array length: 3288
```

I'm seeing the same error in [Don Mccurdy's glTF Viewer](https://gltf-viewer.donmccurdy.com/), though the [official glTF validator](https://github.khronos.org/glTF-Validator/) doesn't seem to show any issues and the [Babylon Viewer](https://sandbox.babylonjs.com/) _can_ load the individual files. Either way glTF loading is outside hte scope of this project since the loader is maintained by three.js. I recommend making an issue at [mrdoob/three.js](https://github.com/mrdoob/three.js) to see where the issue might be.
